chore(precommit): use ruff
Replace black and flake8 with ruff. Currently flake8 produces an internal error:

  AttributeError: 'EntryPoints' object has no attribute 'get'

Which is related to incompatibility with importlib-metadata package version.
We bring the configuration from trame v3.7.6.